#!/usr/bin/env bun
// Emit a hand-rolled service worker into out/sw.js with a fresh version stamp
// and a precache list derived from the static export.
//
// Strategy:
//   - Precache: home page, 404, manifest, icons, articles.json (if present),
//     and every article HTML page.
//   - Runtime cache:
//       * /_next/static/* -> cache-first (immutable hashed assets)
//       * navigation requests (HTML) -> stale-while-revalidate
//       * articles.json -> network-first w/ cache fallback (currently inlined,
//         but harmless if we ever serve it at runtime)
//
// next-pwa is unmaintained for App Router static export and tends to clash with
// `output: "export"`. Hand-rolled is ~80 lines and survives upgrades.

import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "out");

if (!existsSync(OUT)) {
  console.error("No out/ directory. Run `next build` first.");
  process.exit(1);
}

// Version stamp: prefer Library.generatedAt for traceability, fall back to now.
let version = `t-${Date.now()}`;
const libPath = path.join(ROOT, "content", "articles.json");
if (existsSync(libPath)) {
  try {
    const lib = JSON.parse(readFileSync(libPath, "utf8")) as { generatedAt?: string };
    if (lib.generatedAt) version = `v-${lib.generatedAt}`;
  } catch {
    /* fall through to timestamp */
  }
}

// Precache list: walk out/ for the small set of must-haves. Don't precache
// every external resource — only things actually emitted under out/.
const precache = new Set<string>(["/"]);

function relPath(absFile: string): string {
  // out/foo/bar.html -> /foo/bar.html ; out/article/x/index.html -> /article/x/
  const rel = "/" + path.relative(OUT, absFile).split(path.sep).join("/");
  if (rel.endsWith("/index.html")) return rel.slice(0, -"index.html".length);
  return rel;
}

function walkArticles() {
  const articleRoot = path.join(OUT, "article");
  if (!existsSync(articleRoot)) return;
  for (const slug of readdirSync(articleRoot)) {
    const idx = path.join(articleRoot, slug, "index.html");
    if (existsSync(idx)) precache.add(relPath(idx));
  }
}

function addIfPresent(rel: string) {
  if (existsSync(path.join(OUT, rel.replace(/^\//, "")))) precache.add(rel);
}

walkArticles();
addIfPresent("/manifest.webmanifest");
addIfPresent("/icon-192.png");
addIfPresent("/icon-512.png");
addIfPresent("/apple-touch-icon.png");
addIfPresent("/articles.json");
addIfPresent("/search-index.json");
addIfPresent("/404.html");

const PRECACHE = Array.from(precache).sort();

const sw = `// LibStack service worker — generated by scripts/build-sw.ts
// version: ${version}
// precaches: ${PRECACHE.length} entries
const VERSION = ${JSON.stringify(version)};
const STATIC_CACHE = "libstack-static-" + VERSION;
const RUNTIME_CACHE = "libstack-runtime-" + VERSION;
const PRECACHE = ${JSON.stringify(PRECACHE)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(STATIC_CACHE).then((cache) =>
      // Use {cache: "reload"} so install always pulls fresh from network, not HTTP cache.
      cache.addAll(PRECACHE.map((u) => new Request(u, { cache: "reload" })))
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((k) => k !== STATIC_CACHE && k !== RUNTIME_CACHE)
          .map((k) => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

function isStaticAsset(url) {
  return url.pathname.startsWith("/_next/static/")
      || url.pathname.endsWith(".png")
      || url.pathname.endsWith(".svg")
      || url.pathname.endsWith(".webmanifest")
      || url.pathname.endsWith(".ico");
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(RUNTIME_CACHE);
  const cached = await cache.match(request);
  const network = fetch(request)
    .then((res) => {
      if (res && res.ok) cache.put(request, res.clone());
      return res;
    })
    .catch(() => cached);
  return cached || network;
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return cached;
  const res = await fetch(request);
  if (res && res.ok) {
    const cache = await caches.open(RUNTIME_CACHE);
    cache.put(request, res.clone());
  }
  return res;
}

async function networkFirst(request) {
  const cache = await caches.open(RUNTIME_CACHE);
  try {
    const res = await fetch(request);
    if (res && res.ok) cache.put(request, res.clone());
    return res;
  } catch {
    const cached = await cache.match(request);
    if (cached) return cached;
    throw new Error("offline and no cache for " + request.url);
  }
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  if (url.pathname.endsWith("/articles.json") || url.pathname === "/articles.json") {
    event.respondWith(networkFirst(req));
    return;
  }

  if (url.pathname.endsWith("/search-index.json") || url.pathname === "/search-index.json") {
    event.respondWith(networkFirst(req));
    return;
  }

  if (isStaticAsset(url)) {
    event.respondWith(cacheFirst(req));
    return;
  }

  // Navigation / HTML
  if (req.mode === "navigate" || (req.headers.get("accept") || "").includes("text/html")) {
    event.respondWith(staleWhileRevalidate(req));
    return;
  }

  // Default: cache-first for anything else same-origin
  event.respondWith(cacheFirst(req));
});
`;

const outPath = path.join(OUT, "sw.js");
writeFileSync(outPath, sw);
console.log(`Service worker: wrote ${path.relative(ROOT, outPath)} (version ${version}, ${PRECACHE.length} precache entries)`);
